import { MovieCard } from "@/components/card/card";
import useMovies from "@/lib/hooks/useMovies";
import Head from "next/head";

const NowPlaying = () => {
  const { movies } = useMovies();

  return (
    <>
      <Head>
        <title>Now Playing | cinemov</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <div className="items-center flex flex-col">
        <div className="grid gap-5 p-5 w-fit  truncate grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          {movies.map((movie: any, id: number) => (
            <MovieCard
              key={id}
              imgUrl={movie.poster_url}
              title={movie.title}
              id={movie.id}
              trailerUrl={movie.trailer_url}
            />
          ))}
        </div>
      </div>
    </>
  );
};
export default NowPlaying;
