import { Header } from "@/components";
import { db } from "@/lib/firebase/firebase.config";
import { getSession } from "next-auth/react";
import Head from "next/head";
import { useEffect } from "react";

// list of movie
// export async function getServerSideProps(context: any) {
//   // Fetch data from external API
//   const session = await getSession(context);
//   let data = db
//     .collection("balance")
//     .doc()
//     .get()
//     .then((res) => {
//       return res.data();
//     });

//   return { props: { data } };
// }

interface NowPlayingProps {
  data: any;
}

const NowPlaying = (props: NowPlayingProps) => {
  const { data } = props;

  console.log(data);

  return (
    <>
      <Head>
        <title>Now Playing | cinemov</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <div className=""></div>
    </>
  );
};
export default NowPlaying;
