import HomeBanner from "@/components/homepage/banner";
import { NextPage } from "next";
import Head from "next/head";
import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation, Pagination, Scrollbar, A11y } from "swiper";
import "swiper/css";

import { getSession, useSession } from "next-auth/react";
import {
  createBalance,
  getAccount,
  getBalance,
  getMovie,
  getUser,
} from "@/lib/firebase/db";
import { useEffect } from "react";
import useUser from "@/lib/hooks/useUser";
import useData from "@/lib/hooks/useMovies";
import { getBooked } from "@/lib/firebase/methods/dbGet";
import useMovies from "@/lib/hooks/useMovies";
const Index = () => {
  const { movies } = useMovies();
  const { user } = useUser();

  useEffect(() => {
    // if (user) {
    //   const data = getBooked(user?.id);
    //   if (data) {
    //     data.then((res) => {});
    //   }
    // }
  }, [movies]);
  return (
    <>
      <Head>
        <title>cinemov</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <div className="bg-gray-800 w-full flex justify-center pt-10 pb-24 px-20 gap-12 ">
        <HomeBanner />
      </div>
    </>
  );
};

export default Index;
