import HomeBanner from "@/components/homepage/banner";
import { NextPage } from "next";
import Head from "next/head";
import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation, Pagination, Scrollbar, A11y } from "swiper";
import "swiper/css";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>cinemov</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <div className="bg-gray-800 w-full flex justify-center pt-10 pb-24 px-20 gap-12 ">
        <HomeBanner />
      </div>
    </>
  );
};

export default Index;
