import { Header } from "@/components";
import ConfirmDelete from "@/components/modal/confirmDelete";
import Head from "next/head";
import React from "react";

export default function Layout({ children }: React.PropsWithChildren<{}>) {
  return (
    <>
      <Head>
        <title>cinemov</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <Header />
      <div className="container mx-auto px-5 max-w-screen-2xl">{children}</div>
    </>
  );
}
