import { useModal } from "@/lib/hooks/useModal";
import Header from "@/components/header/header";
import Head from "next/head";
import React, { useEffect } from "react";

export default function Layout({ children }: React.PropsWithChildren<{}>) {
  const { isActiveModal, setInActiveModal } = useModal();
  useEffect(() => {
    if (isActiveModal) {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "unset";
    }
  }, [isActiveModal]);
  return (
    <>
      <Head>
        <title>cinemov</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <Header />
      <div className="container mx-auto px-0 max-w-screen-2xl">{children}</div>
      <div
        className={`${
          isActiveModal
            ? "fixed w-screen h-screen top-0 left-0 right-0 bottom-0 bg-[rgba(0,0,0,0.5)] z-100 cursor-pointer"
            : "hidden"
        }`}
        onClick={setInActiveModal}
      ></div>
      {/* </div> */}
    </>
  );
}
